name: limablu_mobile
description: LimaBlu mobile app
# add this:
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  fl_chart: ^0.66.0
  intl: ^0.19.0
  google_fonts: ^6.3.0
  path_provider: ^2.1.4
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true
  assets:
    - .env